name: Release
on:
  push:
    tags:
    - 'v*'

jobs:
  image:
    name: Push Container Image
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build images
      run: |
        docker build -t echo:dev .
    - name: Login to ghcr.io
      run: echo ${{ secrets.CR_PATH }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - name: Push images
      run: |
        TAG=${GITHUB_REF#refs/tags/v}
        docker tag echo:dev ghcr.io/hk220/echo:$TAG
        docker push ghcr.io/hk220/echo:$TAG
